# Generated by Django 4.0.6 on 2023-11-23 16:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authors', '0003_userprofuile_currently_hacking_on_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfuile',
            new_name='UserProfile',
        ),
    ]
