# Generated by Django 4.0.6 on 2023-11-23 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_rename_userprofuile_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='currently_hacking_on',
            new_name='currently_working_on',
        ),
    ]
