# Generated by Django 4.0.6 on 2023-11-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_blog_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='post_image',
            field=models.ImageField(blank=True, upload_to='imgblog/'),
        ),
    ]
